apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2019-12-10T09:44:12Z"
    generation: 1
    labels:
      app: quotesapi
    name: quotesapi
    namespace: subhadipdhar-quotes-dev
    resourceVersion: "54161119"
    selfLink: /apis/image.openshift.io/v1/namespaces/subhadipdhar-quotes-dev/imagestreams/quotesapi
    uid: 9f62fecf-1b31-11ea-93e7-0a580a80013d
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/subhadipdhar-quotes-dev/quotesapi
    publicDockerImageRepository: default-route-openshift-image-registry.apps.ocp-na1.prod.nextcle.com/subhadipdhar-quotes-dev/quotesapi
    tags:
    - items:
      - created: "2019-12-10T09:46:30Z"
        dockerImageReference: image-registry.openshift-image-registry.svc:5000/subhadipdhar-quotes-dev/quotesapi@sha256:1708504ce8da8ffd3f4f923339b14556fa3c087a8def0e36077fd0476ac121a6
        generation: 1
        image: sha256:1708504ce8da8ffd3f4f923339b14556fa3c087a8def0e36077fd0476ac121a6
      tag: latest
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: "2019-12-10T09:43:32Z"
    creationTimestamp: "2019-12-10T09:43:32Z"
    generation: 2
    name: quotesdb
    namespace: subhadipdhar-quotes-dev
    resourceVersion: "54159916"
    selfLink: /apis/image.openshift.io/v1/namespaces/subhadipdhar-quotes-dev/imagestreams/quotesdb
    uid: 86f91edc-1b31-11ea-8648-0a580a810062
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: image-registry.openshift-image-registry.svc:5000/openshift/mysql:5.7
      generation: 2
      importPolicy: {}
      name: "5.7"
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/subhadipdhar-quotes-dev/quotesdb
    publicDockerImageRepository: default-route-openshift-image-registry.apps.ocp-na1.prod.nextcle.com/subhadipdhar-quotes-dev/quotesdb
    tags:
    - conditions:
      - generation: 2
        lastTransitionTime: "2019-12-10T09:43:32Z"
        message: 'Internal error occurred: Get https://image-registry.openshift-image-registry.svc:5000/v2/:
          x509: certificate signed by unknown authority'
        reason: InternalError
        status: "False"
        type: ImportSuccess
      items: null
      tag: "5.7"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
